apiVersion: v1
kind: Service
metadata:
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "pinpoint-web.fullname" . }}
  labels:
{{ include "pinpoint-web.labels" . | indent 4 }}
spec:
  ports:
    - name: ui
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}

  selector:
{{ include "pinpoint-web.selectorLabels" . | indent 6 }}